public enum SoundName // Перечесление звуков, что бы избежать строки (ПРОВЕРИТЬ НАЗВАНИЕ аудио клипов В ИЕРАРХИИ)
{
    DefaultEmpty,
    DeathCry,
    DestructionCrate,
    DoorClosed,
    DoorOpen,
    GrenadeExplosion,
    GrenadeSmoke,
    GrenadeStun,
    GrenadeThrow,
    Heal,
    HookPull,
    HookShoot,
    Interact,
    Move,
    Shoot,
    Spotter,
    Sword
}